### ISSUE TITLE
Rewrite into FSM to manage complexity

### ISSUE THREAD

**Issue by anchpop** [marigold-dev/deku#116]
The code is becoming complex and difficult to understand. It would be helpful if we used an abstraction like an FSM to simplify it. I have a draft of what that would look like here: https://github.com/marigold-dev/sidechain/blob/flowchart_rewrite_proposal/bin/flowchart_rewrite.re

One nice thing about this is that it would allow us to record all the states the node runs through, which would in some cases greatly simplify debugging. This change seems big but I would be happy to spend a day trying to implement it to see how feasible it is.

**Comment by callistonianembrace** [comment]
Does the draft have a complete list of primitives you have in mind? Is there anything more to add? 

Clarification: Not asking for the implementation helpers ofcourse.

**Comment by callistonianembrace** [comment]
Q: Can this model state transitions that depends side effects?

**Comment by anchpop** [comment]
@callistonianembrace 

 > Can you add an example there of a transition the depends on effectful computations?
 
In the [flowchart](https://whimsical.com/sidechain-Hn48PizK75qk4weaU1GuVA) under `Received signature`, the `is_block_present` check requires checking something that I can't easily see how to include in the state machine (specifically, whether the block is present in the list of known blocks, even though the list of known blocks isn't part of the state machine's state). 

> Does the draft have a complete list of primitives you have in mind? Is there anything more to add?

I'm not sure what you mean by this, I think the draft includes everything I have in mind but when implementing it I'm sure I'll realize there's something I forgot haha

**Comment by d4hines** [comment]
We've achieved this in v1 :+1:
