### ISSUE TITLE
clean top level driven experience

### ISSUE THREAD

**Issue by EduardoRFS** [marigold-dev/deku#118]
I would like if we could upstream some of the work on #46 to utop or dune so that rtop can be integrated automatically on it.

A standard `dune utop` that detected that most of the project is in Reason or `dune utop` where you can setup an automated `#required "rtop";;` that changes the parser of utop would also do it.

## Related

#46

**Comment by callistonianembrace** [comment]
This is what we want to achieve

```sh
#! /bin/sh

set -e

TMPDIR="$cur__target_dir/tmp";
mkdir -p $TMPDIR;
dune top | sed "s/\;\;/\;/g" > "$TMPDIR/$cur__name.re";
rtop -init "$TMPDIR/$cur__name.re" "$@"
```

This script also replaces #46

**Comment by d4hines** [comment]
Dune utop works fine now.
