### ISSUE TITLE
running ligo on sidechain

### ISSUE THREAD

**Issue by EduardoRFS** [marigold-dev/deku#163]
### Old

- [x] create reproducible ligo dev environment
- [x] compile ligo to zinc
- [x] write binary wrapper for ligo
- [x] #289
- [x] modify zinc interpreter to support named terms
- [x] Everything in zinc-types that depends on ligo should be removed
- [x] zinc-types (and probably the zinc interpreter actually but I think that can wait) needs to be moved out of ligo and into a separate package 
- [x] modify zinc interpreter to support exceptions
- [ ] modify zinc interpreter to include explicit "done" operations (not sure this is a good idea...)
- [x] add strings to zinc
- [ ] implement mathy functions on zinc (hash, euclidian division, bytes.pack, etc.)
- [x] make ligo build with esy

### What is a contract?

A contract is a piece of user defined code, coupled to a piece of storage that it controls, this code can be executed externally or internally and it is allowed to trigger on chain operations.

### Contracts on deku

- [x] #293
- [ ] #294
- [ ] #295
- [ ] #296

Related: #278

**Comment by anchpop** [comment]
Good first projects

- [ ] Add an operation that originates a contract 
- [ ] Add lists to Zinc
- [ ] Remove label names from Zinc (replace with arrays & integers)

**Comment by d4hines** [comment]
We're doing ligo through michelson now.
