### ISSUE TITLE
support tz2 on tezos_interop

### ISSUE THREAD

**Issue by EduardoRFS** [marigold-dev/deku#199]
Subst of #22, tz2 uses secp256k1 which I believe are not directly supported by mirage-crypto-ec.

- [x] Ask the authors of mirage-crypto-ec about it

**Comment by EduardoRFS** [comment]
Indeed secp256k1 is not supported by mirage-crypto-ec, maybe we should switch to hacl-star.

**Comment by Zett98** [comment]
> Indeed secp256k1 is not supported by mirage-crypto-ec, maybe we should switch to hacl-star.

Hacl-star doesn't support it either, but there is a library from nomadic labs
