### ISSUE TITLE
Validator on consensus contract should be a key_hash

### ISSUE THREAD

**Issue by EduardoRFS** [marigold-dev/deku#202]
The validator on the consensus.mligo contract should be represented as a key_hash to match #201 change on the Deku side.

The ligo compiler should be able to help to ensure that all the places were properly fixed. https://ligolang.org/

https://github.com/marigold-dev/deku/blob/main/tezos_interop/consensus.mligo#L4

**Comment by rosalogia** [comment]
Closed by #208
