### ISSUE TITLE
./setup.sh produces invalid configuration

### ISSUE THREAD

**Issue by Zett98** [marigold-dev/deku#213]
As in title.

**Comment by EduardoRFS** [comment]
Which invalid configuration?

**Comment by EduardoRFS** [comment]
@Zett98 was the problem addressed or it was just a mistake of you?

**Comment by anchpop** [comment]
@Zett98 what should be the contents of `trusted-validator-membership-change.json`?

**Comment by d4hines** [comment]
No longer relevant since this code is long gone.
