### ISSUE TITLE
Make `required_confirmations` configurable

### ISSUE THREAD

**Issue by d4hines** [marigold-dev/deku#273]
Currently `sidecli` generates config that sets `required_confirmations` to 10. Perhaps this is required for production, I'm not sure. But for development it gives the illusion that the chain is just stalled. Setting to `1` makes things run much faster.

We should either have a lower default or (better option) make it configurable on the command line, or maybe both.

**Comment by EduardoRFS** [comment]
Oh reading now about making it configurable, don't think this is a good idea, it's a private property that should not change outside of development environments.

**Comment by d4hines** [comment]
No longer needed as of Tenderbake 🎉
