### ISSUE TITLE
Ligo on sidechain prototype 1 (single contract)

### ISSUE THREAD

**Issue by anchpop** [marigold-dev/deku#278]
**Proto 1**: A single static contract that resends any money you send to it to me

- [x] talk to ligo people about writing a function for compiling a string that doesn't require writing it to a file first
- [ ] modify zinc interpreter to support ADTs
   - [x] products
   - [x] matching on sums
   - [ ] lists
- [x] add operation for invoking contract
- [x] implement get_contract_opt
- [x] execute contract
- [x] interpret contract's output (which will be to send money to me)
- [ ] and then execute that too

**Comment by d4hines** [comment]
We have Tunac compiler for this now.
