### ISSUE TITLE
Define smart contract IR

### ISSUE THREAD

**Issue by EduardoRFS** [marigold-dev/deku#291]
We choose Zinc, why did we choose Zinc? What is Zinc? References on Zinc(blog post)?

**Comment by anchpop** [comment]
Good questions

1) Zinc is an abstract machine like LC or turing machines. Compilation from LC to Zinc is basically trivial but zinc can be evaluated straightforwardly in an efficient manner 
2) So we we needed an abstract machine, these were our options:
   1. LC - pros: compilation is a no-op, cons: execution is slow
   2. SECD and CEK: strict but don't support currying very well (
   3. Krivine: supports currying but is lazy (ligo semantic are strict)
   4. Zinc: Strict and very similar to SECD, but with some extra instructions to support currying
   5. Crazy things I don't understand like Lamping's algorithm for optimal sharing
   So Zinc it is 
3) [Intro to Zinc that I wrote](https://www.marigold.dev/post/efficiently-implementing-the-lambda-calculus-with-zinc)
