### ISSUE TITLE
Define execution model

### ISSUE THREAD

**Issue by EduardoRFS** [marigold-dev/deku#292]
Which model? What is an execution model? How does one update the state? How does one do a transfer?

**Comment by anchpop** [comment]
A contract is a function `parameter -> storage -> (operation list, storage)`. When a contract is originated, an initial storage is provided. After contract invocation, the output is interpreted so the operations are executed and the storage is updated. Unless a contract fails or the user runs out of gas, in which case the change to the storage is rolled back.

**Comment by anchpop** [comment]
The execution model is more subtle. In every block, there will be some number of *contract invocations*. The same contract may be invoked multiple times in a block, and in that case the order in which the invocations are processed must be identical for all nodes. Additionally, each contract can itself invoke other contracts. If 

@EduardoRFS has suggested that each contract invocation present in a block should include a set of contracts that may be transitively invoked. If a contract attempts to invoke another that isn't in that set, the operation fails (and probably each member in the set costs some amount of gas). I think that's a good suggestion. 

A straightforward method would be to just execute the contracts in the order they appear in the block. But we want to execute non-interacting contract invocations in parallel. I think that any invocations that share no contracts in common can be safely executed in parallel. A precise specification for the order of contract execution is necessary, but still unclear to me. 

One possible approach:

Whether or not two contract invocations interact is determined by whether the sets of contracts they can invoke intersect. You can imagine a graph where nodes are contract invocations and edges connect invocations that don't interact. If two contracts have an edge connecting them, they're safe to execute in parallel. So a straightforward strategy would be to divide the graph into cliques, and then within a clique the invocations can be processed in parallel but the cliques themselves would have to be processes in some well-defined order.

**Comment by EduardoRFS** [comment]
Keeping this open until all the details are settled, but for me it's a good enough PR.
