### ISSUE TITLE
Zinc optimizations

### ISSUE THREAD

**Issue by anchpop** [marigold-dev/deku#358]
## Optimize functions that take records

currently `function lf (const d: bool; const c: bool) : int is ...` generates bad code for three reasons. 

- [ ] That code could be equivalent to this:

   ```
   let lf = lambda (parameters#745) return match parameters#745 with
     | ( a , b ) -> ...
   ```

   But instead the code we're compiling is analogous to this:

   ```
   let lf = lambda (parameters#745) return let #784 = parameters#745 in 
     match #784 with
     | ( a , b ) -> ...
   ```

   I'm not sure why. I think it's ligo doing that transformation, in which case we could add a pass over the AST to remove `let x = y in ...` because they have no effect semantically. Either that or it's us doing that transformation (wouldn't be surprising, we do transform the AST in compile_pattern_matching and there could be a bug in there)

- [ ] Once we actually compile the match, we do something like this:

   ```
   let lf = lambda (parameters#745) return let #784 = parameters#745 in 
     let #786 = #784 in let b = #786.1 in let a = #786.0 in ...
   ```

   So now we've introduced `let #786 = #784 in ...` for a new total of *two* layers of no-op lets. This one is definitely our fault - you can fix it by editing `compile_pattern_matching` to not generate a fresh variable if `to_match.matchee` is an `E_variable`. 

- [ ] Okay, so let's say we've fixed those two issues and we're compiling the equivalent of this ligo:

   ```
   let lf = lambda (parameters#745) return let b = parameters#745.1 in let a = parameters#745.0 in ...
   ```

   But because of how compile_pattern_matching is written, it always will compile this as if it's a non-tail call, even though it's a tail call, which generates much worse code than necessary. I think I have an idea for how to fix this so I'll fix it tomorrow

## Optimize variants

The same optimization @Zett98 did with records, where they went from a map from strings to stack_items. to an array of stack_items, should be done with variants too

**Comment by d4hines** [comment]
No longer using zinc.
