### ISSUE TITLE
ensure uniqueness of hashes

### ISSUE THREAD

**Issue by EduardoRFS** [marigold-dev/deku#359]
A potential attack is if two pieces of data have the same format an user signature can be reused to a different intent.

This is unlikely in general, but it would be great to have at least a centralized place that take care of all hashes.

**Comment by oteku** [comment]
> it happens as soon as the format of two data structures are similar

A solution would be to have non counter unique ids in all data structures for this purpose

**Comment by d4hines** [comment]
This is addressed in our new crypto library.
