### ISSUE TITLE
update deku compiler version for algebraic effects

### ISSUE THREAD

**Issue by anchpop** [marigold-dev/deku#374]

**Comment by Zett98** [comment]
postponed for now

**Comment by EduardoRFS** [comment]
Last try a month ago there was problems with @opam/fix but maybe it it's fixed as there is a new release.

**Comment by anchpop** [comment]
I think algebraic effects may be a good fit for gasification of the zinc interpreter

**Comment by d4hines** [comment]
We have OCaml5, yay. But effects are still untyped 😢
