### ISSUE TITLE
Develop plan for tickets

### ISSUE THREAD

**Issue by anchpop** [marigold-dev/deku#381]
Tickets (I think) should be able to be stored in contract storage, for compatibility with tezos. That means we need a way to enforce linearity. I think the way to do that will be to identify the (limited) number of non-linear operations on zinc and mark the copies of the ticket as "destroyed" when those are used. But I have no idea how to do this this in a way that I'm confident will be correct

**Comment by EduardoRFS** [comment]
A contract may work on Deku but no on Tezos sure, but what we care is that if a contract works on Tezos it works on Deku.

And for that we don't need linearity or tickets in the storage. Tickets as in a first class value are not the same as tickets in being a token.

**Comment by anchpop** [comment]
@EduardoRFS Do you think the plan that GA recommended (outlined in #382) is compatible with the goal of deku back-compatibility with tezos?

**Comment by d4hines** [comment]
This is being handled elsewhere. Closing this issue.
