### ISSUE TITLE
Tendermint-in-Deku

### ISSUE THREAD

**Issue by AngryStitch** [marigold-dev/deku#435]
## Depends 

- [ ] #432 
- [ ] #433 
- [ ] #434 
- [ ] #436

## Problem

We need a new consensus in Deku.

## Solution 

Get [Tendermint as defined in Algorithm 1, page 6](https://arxiv.org/pdf/1807.04938.pdf) in Deku.

**Comment by d4hines** [comment]
We're leaning away from Tendermint and probalby towards HotStuff.
