### ISSUE TITLE
New Networking Layer

### ISSUE THREAD

**Issue by rosalogia** [marigold-dev/deku#440]
We would like to improve Deku's networking layer such that it is simpler, more reliable, and maintains performance.

Currently a major issue with the networking layer is that if we have some peers, A, B, and C, such that:

* A and C are peers
* C and B are peers
* A and B are not peers

and A broadcasts a message, C will receive it, but B will not. This is incorrect behaviour. The networking layer should be reworked such that so long as there is a path between A and B, regardless of whether or not A and B are peers, any message broadcasted by A should be received by B and vice versa. At the same time, this should be done in a way that avoids sending O(n^2) messages.

In the process of achieving this, there are various sub-goals that will help generally improve the quality of the networking layer, including:

- [ ] #441 
- [x] #442
- [x] #443

**Comment by d4hines** [comment]
We fixed the bugs in connectivity but still have O(n^2) communication. Closing this issue - we will address improving gossip separately.
