### ISSUE TITLE
Decide on a serialization format

### ISSUE THREAD

**Issue by rosalogia** [marigold-dev/deku#442]
As mentioned in #440, in order to simplify our networking layer we would like to switch away from HTTP/JSON to UDP/Bin_prot.

**Comment by d4hines** [comment]
It's not obvious that bin_prot is the serialization format we ultimately want. The design space is quite large and it's hard to know ahead of time what will work best. Some other libraries to consider are Data_encoding (which is well supported by Tezos ecosystem and has JSON outputs "for free") and Capn Proto (which may be as or more performant than bin_prot but with better langauge support).

**Comment by d4hines** [comment]
We're going with Data_encoding for now 👍
