### ISSUE TITLE
Implement minimal logging

### ISSUE THREAD

**Issue by oteku** [marigold-dev/deku#568]
SUMMARY: 
Have a logging module in DEKU

MOTIVATION: 

We can observe that:
- L2 commit blocks on L1
- We want to observe:
        logging =
            logging consensus role & steps => LEVEL INFO
            logging functional errors (observable) => LEVEL ERROR
            logging warnings (exemple timeout) => LEVEL WARNING

    
DETAILED DESIGN: TODO

ALTERNATIVES: TODO

DRAWBACKS: TODO

RELATED PRs:
- [ ]

**Comment by aguillon** [comment]
https://erratique.ch/software/logs/doc/Logs/index.html and make sure logging is non-blocking

**Comment by d4hines** [comment]
Related #285

**Comment by ulrikstrid** [comment]
Related #623

**Comment by d4hines** [comment]
We're using Logs. There's work to be done but I think we can close this issue.
