### ISSUE TITLE
Automatize operations on demonet

### ISSUE THREAD

**Issue by oteku** [marigold-dev/deku#569]
SUMMARY:
We want to have some recurrent operation running on DEKU Demonet to observe the network

MOTIVATION: Gain better confidence in DEKU

SCENARII: TODO

DETAILED DESIGN: TODO

ALTERNATIVES: TODO

DRAWBACKS: TODO

RELATED PRs:
- [ ]

PREREQUISITES:
- #566

**Comment by d4hines** [comment]
This is handled by deku tester.
