### ISSUE TITLE
Setup for benchmarks

### ISSUE THREAD

**Issue by lykimq** [marigold-dev/deku#575]
# Summary

Providing a setup to be able to run the benchmarks easily and get reproducible (whenever possible) results.

# Motivation

We want benchmarks that we can easily run on a new version of the code to compare results. Running (some of) the benchmarks against a new version could also be automatized. 

# Production

???

**Comment by d4hines** [comment]
PR #539 provides e2e benchmarks, but they are neither easy to get at not automated (you have to go and configure the prometheus server to do the visualizations you want in the web interface). But it might provide a starting point.

**Comment by d4hines** [comment]
current-bench also has a pretty web interface for comparing benchmarks results, but I'm not sure it's worth the setup and maintenance - that's a conversation between @lykimq, @InfiniteSwerve and infra.

**Comment by lykimq** [comment]
> ~current-bench also has a pretty web interface for comparing benchmarks results, but I'm not sure it's worth the setup and maintenance - that's a conversation between @lykimq, @InfiniteSwerve and infra.~
> 
> ~In my MR to Tezos, I used the current-bench frontend to visualize core_bench microbenchmark results collected in Gitlab actions, but it was a pain to setup since current-bench was designed to work with ocurrent, not Github/Gitlab actions.~
> 
> I'm actually out of date - it looks like they've added first-class support for my original use case: https://github.com/ocurrent/current-bench#using-api-to-submit-benchmark-data Probably worth checking out again.
So as we discussed at this moment, for the current-bench we will not consider it as a tool we want to use.

**Comment by d4hines** [comment]
`nix run github:marigold-dev/benchmark`. Anywhere. Anytime. ❤️
