### ISSUE TITLE
Deku performance metrics

### ISSUE THREAD

**Issue by d4hines** [marigold-dev/deku#602]
Keep in mind Prometheus collects timestamps on every sample and has a query language to do many transformations. Refer to its docs.

Things we want to measure with Prometheus:
- [x] block rate
- [x] transaction rate
- [x] incoming message size/rate
- [ ] how long does it take to broadcast a new block (should not be a lot, but it's a good metric to compare with the total time of a block, e.g. "of the total block rate X, we spend Y% hashing, signing, and serializing the new block")
- [ ] mempool size for each node

**Comment by d4hines** [comment]
cc @lykimq @InfiniteSwerve

**Comment by ulrikstrid** [comment]
Are the queries used documented somewhere? I want to add it to the grafana instance for our testnet

**Comment by d4hines** [comment]
This is being handled elsewhere.
