### ISSUE TITLE
Use Cmdliner to decide logging level and reporter

### ISSUE THREAD

**Issue by ulrikstrid** [marigold-dev/deku#623]
Now that #604 is merged we are starting to use `Logs` for logging.

Since we don't want to always have the JSON output because readability is bad for users we used a environment variable to decide what reporter to use.
A better solution would be to have a flag when starting the node about what reporter to use. While we're at it we can also use `Logs_cli` to set the verbosity of the logging.

**Comment by aguillon** [comment]
https://github.com/marigold-dev/deku/pull/285

I think we're good with this one?
