### ISSUE TITLE
Test cases for consensus algorithm

### ISSUE THREAD

**Issue by kienle371999** [marigold-dev/deku#721]
# Summary

A consensus algorithm is the heart of any blockchain system. We need to generate test cases to prove that our consensus algorithm is resistant to common attacks.

# Test cases

**Scenario 1**
- We have three nodes: A, B, and C. These are validators in Deku.
- Node A is the proposer. It produces its own block.
- Node A also signs this block and broadcasts its signature.
- Node B and node C receive this block but they don't sign it and broadcast its signature.
- We have **less than 2/3 validators** agreeing on this block so this block isn't included in Deku.

**Scenario 2**
- We have three nodes: A, B, and C. These are validators in Deku.
- Node A is the proposer. It produces its own block.
- Node A also signs this block and broadcasts its signature. 
- Node B receives this block, signs it, and broadcasts its signature.
- Node C receives this block, signs it, and broadcasts its signature.
- Meanwhile, these validators are suddenly interrupted. 
- Therefore, these signatures aren't properly handled by **validators** so this block isn't included in Deku.

**Comment by d4hines** [comment]
We have these already.
