### ISSUE TITLE
Use mkdir_p instead of mkdir in sidecli's setup-node

### ISSUE THREAD

**Issue by anchpop** [marigold-dev/deku#97]
`setup-node` uses mkdir to create the folder the user specifies, but that fails if the user specifies a subdirectory of a folder that doesn't currently exist (it doesn't recursively create subdirectories). A UX improvement would be to use Jane Street core's [mkdir_p](https://ocaml.janestreet.com/ocaml-core/v0.13/doc/core/Core__/Core_unix/index.html#val-mkdir_p) which does have this behavior.

**Comment by d4hines** [comment]
We can close this since we've moved to static config instead of dynamic generation.
